### ISSUE TITLE
Add a requirements file

### ISSUE THREAD

**Issue by joaopcoelho** [sinanuozdemir/pearson-gpt-training-engineer#1]
Hi, just a suggestion to add a requirements file to make it easier to run locally :) thanks for the great work

**Comment by sinanuozdemir** [comment]
Thank you so much!! I did add one and have moved many notebooks to colab to hopefully make it easier too :) I really appreciate the comment

**Comment by sinanuozdemir** [comment]
commit where I added the file: commit 1f58b515d0220e11764a7966b0029f3f8370b9ba
